#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=20

# The parts of ticket 02 that must happen inside Xcode / the Apple Developer
# portal — they need your signing identity, so they can't be scripted. This
# wizard opens the project and walks you through each click. Nothing is written
# to disk; every value already lives in the project's entitlements.

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/ExpenseKu/ExpenseKu.xcodeproj"
CONTAINER_ID="iCloud.randyefan.ExpenseKu"   # already set in ExpenseKu.entitlements

banner "ExpenseKu — finish CloudKit setup (ticket 02)"

# ── Stage 1: open the project & set the signing team ──────────────────────
stage "Signing team" 3
say "CloudKit containers are created under your Apple Developer team, so signing"
say "must be set first."
open_url "$PROJECT"
step "In Xcode: select the ExpenseKu project → TARGETS ▸ ExpenseKu."
step "Open the 'Signing & Capabilities' tab."
step "Tick 'Automatically manage signing'."
step "Set 'Team' to your Apple Developer team."
note "If you have no team, add your Apple ID: Xcode ▸ Settings ▸ Accounts ▸ +."
pause "Signing team set? Press Enter."

# ── Stage 2: add the macOS destination ────────────────────────────────────
stage "Add macOS destination" 3
say "The design targets iOS + iPadOS + macOS from one target. The template only"
say "shipped iPhone/iPad — add Mac now."
step "Still on TARGETS ▸ ExpenseKu, open the 'General' tab."
step "Under 'Supported Destinations', click '+' and add 'Mac (Designed for iPad)'"
say "  — or 'Mac Catalyst' / native 'Mac' if you want a true Mac build."
warn "After adding Mac, return to 'Signing & Capabilities' and confirm the team"
warn "is set for the Mac destination too (the tabs are per-destination)."
pause "macOS destination added? Press Enter."

# ── Stage 3: iCloud + CloudKit capability & container ──────────────────────
stage "iCloud / CloudKit capability" 6
say "Wire the app to a private CloudKit container so SwiftData mirrors across"
say "your devices. The container id is already in the entitlements file:"
note "  $CONTAINER_ID"
step "In 'Signing & Capabilities', click '+ Capability' and add 'iCloud'."
step "Under Services, tick 'CloudKit'."
step "In the Containers list, tick '$CONTAINER_ID'."
say  "If it isn't listed, click '+' below the list, enter exactly:"
note "  $CONTAINER_ID"
say  "then tick it. Xcode creates it in the Developer portal for you."
step "Add the 'Background Modes' capability and tick 'Remote notifications'"
say  "  (CloudKit uses a silent push to trigger sync)."
warn "The container tick must match $CONTAINER_ID exactly, or sync stays silent."
pause "CloudKit container ticked and matching? Press Enter."

# ── Stage 4: verify the container in the dashboard ────────────────────────
stage "CloudKit dashboard" 2
say "SwiftData creates record types the first time it saves while signed in."
say "You don't need to configure anything here now — just confirm the container"
say "exists under your account."
open_url "https://icloud.developer.apple.com/dashboard/"
step "Confirm '$CONTAINER_ID' appears in the container dropdown."
note "Record types will populate after the first synced save (next stage)."
pause "Container visible in the dashboard? Press Enter."

# ── Stage 5: build & run on both platforms ────────────────────────────────
stage "Build iOS + macOS" 3
say "Ticket 02 done-part 1: the app builds and runs on both platforms."
step "Select an iOS Simulator (e.g. iPhone 15) and press Cmd-R — it should launch."
step "Change the run destination to 'My Mac' and press Cmd-R — it should launch too."
warn "If the Mac build fails to sign, revisit Stage 1/2 (team per destination)."
pause "Runs clean on iOS and macOS? Press Enter."

# ── Stage 6: verify cross-device sync ─────────────────────────────────────
stage "Verify sync round-trip" 3
say "Ticket 02 done-part 2: data syncs across devices via CloudKit."
step "Sign both run targets into the SAME iCloud account"
say  "  (Simulator ▸ Settings ▸ sign in; and your Mac's System Settings)."
step "In one instance, add a row (the template's + button)."
step "Wait a few seconds, then confirm it appears in the other instance."
note "First sync can take 10-30s; a relaunch forces a fetch if it lags."
if confirm "Did the row sync across both instances?"; then
  say "${GREEN}CloudKit sync confirmed — ticket 02 is functionally complete.${RESET}"
else
  warn "Not syncing yet. Common causes:"
  note "  - Container tick doesn't match $CONTAINER_ID"
  note "  - Not signed into iCloud, or different accounts"
  note "  - 'Remote notifications' background mode missing (Stage 3)"
  note "  - The template's Item model has a non-optional field — CloudKit needs"
  note "    all attributes optional/defaulted; ticket 03's models fix this."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
